# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.9.0.schema.json
PackageIdentifier: Unlose.unlose
PackageVersion: 1.0.9.7
Installers:
  - Architecture: x64
    InstallerType: wix
    InstallerUrl: https://github.com/unlose-app/unlose/releases/download/v1.0.9/unlose-setup-x64.msi
    InstallerSha256: 19341FBF3CD8A40CC7CF0EF9F32EDA804B12AE223C6B8DDCEA1587B4B99D0951
ManifestType: installer
ManifestVersion: 1.9.0
